export type CSEquery = {
    c2coff?: string;
    cr?: string;
    dateRestrict?: string;
    exactTerms?: string;
    excludeTerms?: string;
    fileType?: string;
    filter?: string;
    gl?: string;
    hl?: string;
    highRange?: string;
    lowRange?: string;
    hq?: string;
    imgColorType?: 'color' | 'gray' | 'mono' | 'trans';
    imgDominantColor?: 'black' | 'blue' | 'brown' | 'gray' | 'green' | 'orange' | 'pink' | 'purple' | 'red' | 'teal' | 'white' | 'yellow';
    imgType?: 'clipart' | 'face' | 'lineart' | 'stock' | 'photo' | 'animated';
    linkSite?: string;
    lr?: string;
    num?: number;
    orTerms?: string;
    relatedSite?: string;
    rights?: string;
    safe?: 'active' | 'off';
    searchType?: 'image';
    siteSearch?: string;
    siteSearchFilter?: 'e' | 'i';
    start?: number;
    sort?: string;
    [key: string]: string | number;
};
